### PR TITLE
Ignore invisible content panes when being dragged

### PR DESCRIPTION
**Pull request by Romout**

### CODE REVIEW

**Comment by Romout** [comment]
I wanted to add an additional Pull-Request but failed. It's related to my last check-in from today 
https://github.com/Romout/dockpanelsuite/commit/c68c5d9ab0a7ee3ffc90df9b200205c26918865c

The purpose is to enable DPS for test automation such as Coded UI or similar. Most parts work out of the box due to standard controls but everything ownerdrawn such as the auto hide elements or dock pane strips require to provide Accessibility Objects in order to be used from outside an application.

Looking forward to your comments.

**Comment by lextm** [comment]
The last check-in looks good to me. But can you clean up the pull request a little bit? Currently it shows 86 commits, which I guess was caused by that you did not merge latest master to your fork yet.

**Comment by Romout** [comment]
It seems as my try to update my forked version to the latest did also introduce all other changes within that time period. Will try my best to clean the mess up.

**Comment by Romout** [comment]
I have to admit, I have no clue on how to remove that obviously failed merge from the pull request. Is merging still possible for you or more like a pain? Otherwise I would need to delete the fork and start all over again (that's the only solution I have in mind for now)

**Comment by Romout** [comment]
I have resubmitted the pull-request. Seems to me that that cleaned up the mess.

**Pull request closed without merging**
