### PR TITLE
Fix multithreading crashes

### PR DESCRIPTION
**Pull request by arhughes**
Fix crashes caused by accessing GraphicsPath and Bitmap objects from multiple threads.

### CODE REVIEW

**Comment by lextm** [comment]
I will close this PR right now and instead cherry pick directly from https://github.com/xo-energy/dockpanelsuite. Will later try to make it easy to use static items as well as instance items based on a new property. That should balance both single thread and multiple threads scenarios.

**Comment by lextm** [comment]
@arhughes I think I can move your multithread support code to a separate theme (`VS2005MultiThreaded`). 

One last question is why do you need to touch `LocalWindowsHook` in https://github.com/xo-energy/dockpanelsuite/commit/b9f3cf8848001093cf5bc6eb8b8aa3cc2a924d7e?

**Comment by lextm** [comment]
@arhughes except the changes on `LocalWindowsHook`, I attempted to merge all other changes back to DPS master.

My approach is as below,

1. Create a new theme, named `VS2005MultithreadingTheme`.
2. Move all your changes into this theme.
3. Restore the previous VS2005 theme.

Why? This keeps better compatibility, as not everyone is using multiple UI threads, and those users should not be bothered by the changes.

Can you test out this new theme in your application to see if there is any further changes needed?

I can see from NuGet.org that your customized DPS package has been downloaded many times, and once you can move to this custom theme instead of a fork your guys maintain separately, you can move to our NuGet packages, and hide your customized one. That can avoid confusion to viewers. Thanks.

**Comment by wjrogers** [comment]
> One last question is why do you need to touch LocalWindowsHook in xo-energy@b9f3cf8?

I wasn't sure if this change was necessary or not -- we were still getting a few "object currently in use elsewhere" crashes, so I simply removed every additional `static` declaration I could find. It's possible that the previous commit fixed it -- I don't remember how thoroughly we tested between those commits.

**Pull request closed without merging**
