### PR TITLE
Resolved #287 (How to save and restore panel configuration within existing XML-structure?)

### LINKED ISSUE #287: How to save and restore panel configuration within existing XML-structure?
Hi there,

actually I know I can use `DockPanel.SaveAsXML()` and `DockPanel.LoadAsXML()` to save and restore my panel configuration. But what I want to do is include that information into my already existing XML-file structure instead creating a single one only for the DockPanel-Configuration.

Let's say I already have a XML-file for my settings:

    <MyApp Content="Configuration" Version="0.1" CreationDateTime="2015-04-21T18:30:04">
      <SomeSettings>
        ...
      </SomeSettings>
      <OpenWindows>
        <MyMainWindowForm>
          <Panels>
            <
          </Panels>
        </MyMainWindowForm>
      </OpenWindows>
      <SomeMoreSettings>
        ...
      </SomeMoreSettings>
    </MyApp>

How can I achieve that? I thought about ´importing´ your XML-Document into mine, but this seems much of overhead for me... It would be nice to just ask for an XMLNode that can be embedded into my XMLDocument, and vice versa give it to DockPanel when restoring the configuration, if you can understand what i'm talking about.

Any ideas? Thanks and regards,
tajbender

### PR DESCRIPTION
**Pull request by tajbender**
- Added "public void SaveAsXml(XmlWriter xmlOut)"
- Added "public void LoadFromXml(XmlTextReader xmlIn, DeserializeDockContent deserializeContent)"

### CODE REVIEW

**Comment by lextm** [comment]
Thanks for sharing the code. The approach so far can lead to some confusion, as it is not obvious which pair should be used in which case.

Ideally it might be converted to strategy pattern, with a default strategy to handle the default XML schema. Then your existing schema can be handled by a custom strategy.

Can you try to explore a little bit further in that direction and update this PR?

@roken What's your opinion?

**Comment by tajbender** [comment]
Hi Lex, thanks for the quick reply. Do you e.g. think of a delegate, which will be called when serializing and accordingly deserializing the own, additional information in the XML-file?

I think of some kind of "DeserializeXMLHeader(XmlTextReader xmlIn)-", respectively "CreateXMLHeader(XmlWriter xmlWriter)"-delegates, which will be null by default?

Keep in mind I want to embed the DockPanel-Infos into my own XML, not my own Information into DockPanels XML-structure, cause in the future I will have lots of additional information that should be stored into my configuration file.

Thanks in advance for your thoughts, regards,
tajbender

**Comment by tajbender** [comment]
Sorry for being late in this. I broke my shoulder, so I was not able to work on any code for months.

However, any change for getting a new Pull Request into 3.0-Release if I would commit it the next hours?

**Comment by lextm** [comment]
@tajbender Sorry to hear that and hope you are fully recovered.

As starting from 3.0 we will ship monthly (#503), don't worry much of this pull request. If it cannot be shipped in August, it can easily be moved to September release.

**Comment by tajbender** [comment]
Thanks for sharing your thoughts on this.

Upcoming is a complete re-implementation of my own code base, and while at it I'll work on this again.

**Comment by tajbender** [comment]
Just for your Information, I'm working an this again.

@lextm: What about introducing two interfaces (for saving and for loading) while providing default behavior which just works exactly as the current code base?

**Comment by tajbender** [comment]
Is solved with "Add PersistString Property #542"

**Pull request closed without merging**
