### PR TITLE
Allow customizing VS2005 elements borders

### PR DESCRIPTION
**Pull request by nanoant**
This is one of the hard-coded elements of VS2005 theme, this change exposes border colors.

### CODE REVIEW

**Comment by lextm** [comment]
Thanks for sharing the changes.

It can stay in a custom VS2005 theme, instead of merging into DPS main repo.

**Comment by nanoant** [comment]
@lextm I am not sure if my PR was misunderstood or something, but it is NOT changing VS2005 theme or creates some new custom theme, but it let's you customize existing VS2005 beyone to what existing interface let's you - as now only fill colors are customizable, but outline (border) colors are hard coded.

**Comment by lextm** [comment]
Customizing the outline color is really an optional feature.

Any feature that,

* Optional
* Suitable for a custom theme (so you can maintain it in a separate project if you like)

is not considered to be accepted via pull requests, due to the restricted resources current maintainers can spend on this project.

**Comment by nanoant** [comment]
@lextm Okay, it is all clear now, thanks for your feedback.

**Comment by lextm** [comment]
You might also check out #571. Starting from upcoming 3.1 release, even the default VS2005 theme lives in a separate NuGet package. That should make it perfect time to publish your updated VS2005 theme on NuGet.org, so others can check it out.

**Pull request closed without merging**
