### PR TITLE
Enable Docking of DockContents similar as ToolBars do

### PR DESCRIPTION
**Pull request by ahuarte47**
This pull implements a new DockArea flag to configure DockContents working similar as a Toolbar does. Activating this flag we can drag the windows in a specific toolbar-panel regardless of normal dock-panels.

The demo application contains a new button to test the behavior of this new toolbar-style DockArea flag.

image

### CODE REVIEW

**Comment by lextm** [comment]
Thanks. Will review it.

**Comment by ahuarte47** [comment]
Thanks a lot @lextm, all advices are welcome.
Alvaro

**Comment by lextm** [comment]
I finished reviewing it, and I think it looks interesting. However, by also reviewing Visual Studio, I can see VS only allows tool bars to be docked at top in a very small area.

Thus, this PR does not help us emulate VS very much, even though it does provide much more powerful possibilities.

Thanks for your hard work. I do not want to merge it right now as the current code base is already massive for us to maintain.

**Comment by lextm** [comment]
@roken What's your opinion? The commits cannot be isolated to a theme, and introduce fundamental changes to how DPS works. Would be difficult to maintain once merged.

**Comment by ahuarte47** [comment]
Thanks a lot @lextm for your review. Whatever the decision, there are few minor changes which fix some issues.

**Dispose Backgroung brush** (https://github.com/dockpanelsuite/dockpanelsuite/pull/337/files#diff-1b818fb6076e88556c615f49593035f5R769)

**Avoid that sometimes MainForm goes bottom in z-order position**(https://github.com/ahuarte47/dockpanelsuite/commit/cef8913e7194642d9d0dfb64c2fc782975c12c9b)

**Fix selection of floating documents** (https://github.com/ahuarte47/dockpanelsuite/commit/062db4b93a7562a41f579eb37c6fb1f25e6cb70b)

**Preserve original bounds of the window** (https://github.com/dockpanelsuite/dockpanelsuite/pull/337/files#diff-2729b2c699fb4a20d75ae135890e811cR915 + https://github.com/dockpanelsuite/dockpanelsuite/pull/337/files#diff-2729b2c699fb4a20d75ae135890e811cR1104 + https://github.com/dockpanelsuite/dockpanelsuite/pull/337/files#diff-a2775188fa1c2be5822053c4407442c1R926 + https://github.com/dockpanelsuite/dockpanelsuite/pull/337/files#diff-a2775188fa1c2be5822053c4407442c1R1264 + https://github.com/dockpanelsuite/dockpanelsuite/pull/337/files#diff-4d077e09f2dc392164298e0f2073ea37R791 + https://github.com/dockpanelsuite/dockpanelsuite/pull/337/files#diff-ca3e011ec3a7931abe9c042a5510d4a9R43)

They can extracted to independent pull requests
Alvaro

**Comment by lextm** [comment]
Thanks. I will review them one by one and cherry pick if needed.

**Pull request closed without merging**
