### PR TITLE
Added a drag event notification. Reason: the layout changed so a user…

### PR DESCRIPTION
**Pull request by Romout**
… might want to save it as soon as order of panels changes.

### CODE REVIEW

**Comment by lextm** [comment]
Thanks. But can you fix whitespace so that your addition matches its surrounding before we merge it?

**Comment by Romout** [comment]
Am 10.10.2015 um 06:45 schrieb Lex Li:
>
> Thanks. But can you fix whitespace so that your addition matches its 
> surrounding before we merge it?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dockpanelsuite/dockpanelsuite/pull/322#issuecomment-147037211>.
>
Yes, sorry. Forgot about that. Will check that in on monday!

**Comment by Romout** [comment]
Using .editorconfig now so that further enhancements on my side will automatically use spaces instead of tabs :-)

**Comment by lextm** [comment]
Thanks, @Romout . The white space issue has been a long time burden for this project (multiple developers use different styles at different stages).

I will soon publish a contributing guide to document out the tips. We will try to fix such issues bit by bit (align with new features and bug fixes), so as to avoid a sudden change on all files which might completely mess up GitHub inline diff view.

**Comment by lextm** [comment]
@roken what's your feedback on this PR? I think it is a good addition.

**Pull request merged**
