### PR TITLE
Added VS2013 style, Created DockPanelSuite logo & Splashscreen, now squashed into 2 commits

### PR DESCRIPTION
**Pull request by thijse**
Same commit, but now re-ordered:
1. VS 2013 Theme. To be more precise, this is the "Blue" theme
2. Minor updates to the DockPanel sample

### CODE REVIEW

**Comment by thijse** [comment]
Hi,

Just curious, have you been able to look at it?

**Comment by lextm** [comment]
Yes, I am reviewing, but bit of slow.

**Comment by thijse** [comment]
Hi,

I'm interested in how the code review is progressing. Please let me know if I can help getting this integrated.

**Comment by lextm** [comment]
This PR involves too many changes, which requires at least one or two months of my spare time. Like @roken points out, there are some changes less likely to be accepted.

I think similar to the case when I merged VS 2012 Light theme in, we will have to do some manual work instead of simply accepting this PR.

I will provide further info once I finish reviewing and experiments on manually merging.

**Comment by lextm** [comment]
Thanks for your patience. Here is the first batch of comments. 

1. Naming is inconsistent. Somewhere I see VS2013Blue, while others use VS2013Light. Should stick to VS2013Blue, as you are trying to build the blue theme, not the light one. (patched)
1. Splitters are not customized to match VS 2013. Thus, the sample looks weird. (patched)
1. VS 2013 has a top bar and a bottm bar which are of `Color.FromArgb(0xFF, 41, 57, 85)`. They should be added to the sample project. (patched)
1. Tab colors are not exactly matching VS 2013, and I see you commented out many elements while porting the VS 2012 theme, such as `lostFocusTab`. You probably have to capture screen shots carefully and compare the pixels.
1. VS 2013 renders an extra rectangle outside each panes, of `Color.FromArgb(0xFF, 142, 155, 188)` and 1 pixel thin. This effect is currently missing in this PR.
1. Dock indicator is also missing in this PR.

I will soon merge your changes to a separate branch (maybe `vs2013blue`) and my patch on the first three issues. Then I will close this PR.

If you are willing to fix the remaining issues, you can leave a comment here and later work on a new PR.

**Comment by lextm** [comment]
The new branch is here, https://github.com/dockpanelsuite/dockpanelsuite/commits/vs2013blue

**Pull request closed without merging**
